### ISSUE TITLE
checksum mismatch issue in Go 1.12.5 darwin/amd64.

### ISSUE THREAD

**Issue by thomloftus** [hashicorp/go-rootcerts#10] opened 2019-06-05 23:59 UTC
I'm having this exact same issue in Go 1.12.5 darwin/amd64.

go clean -modcache doesn't fix it.

locally, I get:
```
verifying github.com/hashicorp/go-rootcerts@v0.0.0-20160503143440-6bb64b370b90: checksum mismatch
	downloaded: h1:VBj0QYQ0u2MCJzBfeYXGexnAl17GsH1yidnoxCqqD9E=
	go.sum:     h1:9HVkPxOpo+yO93Ah4yrO67d/qh0fbLLWbKqhYjyHq9A=
```
so if I then remove the offending line from my go.sum and re-build, all is well.

If I then PR the change to my go.sum file, it fails in Gitlab with the exact opposite checksum mismatch:

```
verifying github.com/hashicorp/go-rootcerts@v0.0.0-20160503143440-6bb64b370b90: checksum mismatch
	downloaded: h1:9HVkPxOpo+yO93Ah4yrO67d/qh0fbLLWbKqhYjyHq9A=
	go.sum:     h1:VBj0QYQ0u2MCJzBfeYXGexnAl17GsH1yidnoxCqqD9E=
```

it would appear that if my go.sum specifies the checksum beginning with VBj, that it should in fact download the same based on:
https://github.com/hashicorp/packer/blob/master/go.sum#L184

very perplexed...

_Originally posted by @thomloftus in https://github.com/hashicorp/go-rootcerts/issues/4#issuecomment-499298450_

**Comment by jefferai** [comment] 2019-06-06 00:32
Duplicate of #9

**Closed by jefferai** 2019-06-06 00:32 UTC

**Comment by jefferai** [comment] 2019-06-06 00:34
BTW a difference with #9 is you are using a non tagged version that doesn't itself have go modules. Try updating to the tag, and if that doesn't work it's the same as #9
